#!/usr/bin/python2

"""
WcTank.com

Usage:
    wct bootstrap
    wct run 

Options:
    bootstrap   Create and populate posts db
    run         Run server.
"""

from wctank import app, db, populate, controller
from docopt import docopt

if __name__ == '__main__':
    args = docopt(__doc__)

    def bootstrap():
        db.create_all()
        populate.updateDb()

    if args['bootstrap'] == True:
        bootstrap()
    
    if args['run'] == True:
        app.run('0.0.0.0')
