#!/usr/bin/python2

"""
WcTank.com

Usage:
    wct dev
    wct bootstrap
    wct run 

Options:
    dev         Bootstrap and run server locally for development.
    bootstrap   Create and populate posts and jobs db
    run         Only run server.
"""

from wctank import app, db
from docopt import docopt

if __name__ == '__main__':
    args = docopt(__doc__)

    if args['dev'] == True:
        db.create_all()
        app.run('0.0.0.0')

    if args['bootstrap'] == True:
        db.create_all()
    
    if args['run'] == True:
        app.run('0.0.0.0')

